stages:
  - upload
  - build
  - sonarqube
  - vendor

image: registry-backend.cic.kz/centras/ckl:latest

.upload:
  tags:
    - ckl
  script:
    - sh upload-app.sh

.build:
  tags:
    - ckl
  script:
    - npm i
    - npm run dev
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --exclude storage --exclude filemanager --exclude filemanager2 --reverse --verbose --delete ./public www/$FTP_DIRECTORY/public bye"
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm
      - node_modules
  variables:
    npm_config_cache: ${CI_PROJECT_DIR}/.npm

.vendor:
  when: manual
  tags:
    - ckl
  script:
    - php -v
    - php composer.phar install
    - lftp -e "open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete ./vendor www/$FTP_DIRECTORY/vendor bye"
  artifacts:
    paths:
      - vendor
    expire_in: 1 week

build-dev:
  extends: .build
  stage: build
  only:
    - main
  variables:
    FTP_DIRECTORY: dev.ckl.kz

upload-dev:
  extends: .upload
  stage: upload
  only:
    - main
  variables:
    FTP_DIRECTORY: dev.ckl.kz

vendor-dev:
  extends: .vendor
  stage: vendor
  only:
    - main
  variables:
    FTP_DIRECTORY: dev.ckl.kz

build-master:
  when: manual
  extends: .build
  stage: build
  only:
    - main
  variables:
    FTP_DIRECTORY: ckl.kz

upload-master:
  when: manual
  extends: .upload
  stage: upload
  only:
    - main
  variables:
    FTP_DIRECTORY: ckl.kz

vendor-master:
  when: manual
  extends: .vendor
  stage: vendor
  only:
    - main
  variables:
    FTP_DIRECTORY: ckl.kz


sonarqube-check:
  stage: sonarqube
  when: manual
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  tags:
    - docker
  variables:
    # SONAR_TOKEN: "4e91a6da8f68c5941ccaa91118b18d3820b921b0"
    # SONAR_HOST_URL: "http://192.168.30.30:8888"
    GIT_DEPTH: 0
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG -Dsonar.sources=. -Dsonar.exclusions=vendor/**,public/**,node_modules/**,storage/**,resources/js/scripts/calc.js,resources/js/dopTOP.js
  allow_failure: true
  only:
    - merge_requests
    - main
